vocabulary.py
bmstu-iu8-g4-2020-project/code2var pull request #10
Opened 2020-10-01 06:23 UTC by RKulagin

2020-10-03 20:34 UTC, mocurin requested changes
Пока не совсем понятно как последний файл так сильно ужался. Надеюсь не придется допиливать по ходу использования

2020-10-03 20:34 UTC, mocurin commented on vocabulary.py
> +        self.index_to_word = {i: word for word, i in zip(self.word_to_index.keys(), self.word_to_index.values())}
dict.items()

2020-10-03 20:34 UTC, mocurin commented on vocabulary.py
> +    def __init__(self, word_freq: typing.List[str], special_words: typing.Optional[Namespace] = Namespace()):
from Typing import List, ...
обычно с typing так работают

2020-10-03 20:34 UTC, mocurin commented on vocabulary.py
> +        self.word_to_index = {word: i for i, word in enumerate([*special_words.__dict__.keys(), *word_freq])}
либо word_freq - странное название, либо тут проблемы с логикой
почему ключи special_words и word_freq (звучит будто это какое-то отображение: слова -> число встреч) дампятся в один массив?

2020-10-03 20:34 UTC, mocurin commented on vocabulary.py
> +    @classmethod
шаришь за разницу между classmethod и staticmethod?

не уверен что тут classmethod уместнее чем staticmethod.
Прув ми ронг

2020-10-03 20:34 UTC, mocurin commented on vocabulary.py
> +        vocab.word_to_index = {word: i for i, word in enumerate(special_words.__dict__.keys())}
сделай, наверное в одном цикле. Генераторы - круто, но не настолько

2020-10-03 20:35 UTC, mocurin commented
И немного больше фрагментируй коммиты. Допилил фичу - сразу заливай

2020-10-04 11:49 UTC, RKulagin commented on vocabulary.py
> +        self.word_to_index = {word: i for i, word in enumerate([*special_words.__dict__.keys(), *word_freq])}
Тут скорее название не такое, word_freq - то, откуда берутся сами слова. Здесь просто words

2020-10-04 11:53 UTC, mocurin commented on vocabulary.py
> +        self.word_to_index = {word: i for i, word in enumerate([*special_words.__dict__.keys(), *word_freq])}
Тогда опиши это в docstring. Заодно глянь в каком формате это описание съест pycharm/твоя ide

2020-10-04 12:28 UTC, RKulagin commented on vocabulary.py
> +    @classmethod
кажется, нужен всё же classmethod, так как cls() выглядит красивее, чем Vocab()

2020-10-04 16:46 UTC, mocurin commented on vocabulary.py
> +    @classmethod
Ну, ахах. С одной стороны да, но с другой - ни один из этих методов не меняет переменные класса, так что по сути является статическим методом. Но оставь, чо уж, мне тоже больше нравится :thinking:

2020-10-04 16:47 UTC, mocurin commented
Названия коммитов поосмысленнее надо бы
Поймешь зачем когда будешь мерджить 10 веток в последнюю ночь)

2020-10-04 16:54 UTC, mocurin approved these changes
В качестве исключения можешь мерджить, но ветку не удаляй. Нужно будет добавить докстринги и пофиксить по мелочам, заодно я может логгирование прикручу

2020-10-04 16:54 UTC, mocurin commented on test_vocabulary.py
> +from itertools import chain
не используется
и вообще месиво какое-то. Сначала все import, затем все from. И обычно в алфавитном порядке

2020-10-04 16:54 UTC, mocurin commented on test_vocabulary.py
> +from itertools import chain
к следующему файлу тоже относится

2020-10-04 17:21 UTC, Ruslan-Kulagin approved these changes

2020-10-04 17:21 UTC, merged