Adopting code2vec
bmstu-iu8-g4-2020-project/code2var pull request #23
Opened 2020-11-19 20:29 UTC by RKulagin

Adopted code2vec preprocessing for code2var net

2020-11-19 21:54 UTC, mocurin submitted a review, later dismissed
Честно говоря - мне прям вообще не нравится отдельная куча опций и жонглирование данными в трех пачках. Было бы круто сделать препроцессинг универсальным - пилить на пути все переданные папки и формировать input_data.vocab. И затем, если нужно, другим скриптом пилить данные на части (тут кстати, можно нормально раскидать данные, чтобы не было такого, что train и val пересекаются по одному имени)

2020-11-19 21:54 UTC, mocurin commented on JavaExtractor/JPredict/src/main/java/JavaExtractor/App.java
> +                executor.execute(new TimeoutCaller(task, s_CommandLineValues.Timeout, task.filename()));
а почему * 10 было?

2020-11-19 21:54 UTC, mocurin commented on JavaExtractor/JPredict/src/main/java/JavaExtractor/Common/Common.java
> +		if (str1==null){
для жабы нет какого-то автоформаттера?

2020-11-19 21:54 UTC, mocurin commented on preprocess.py
> +        word_to_freq.pop("null", 0)
а откуда, еще раз null-ы берутся? Было бы неплохо пихнуть это в докстрингу под NOTE:

2020-11-19 21:54 UTC, mocurin commented on preprocess.py
> +    if args.net == "code2var":
блин, адовое потворение кода. Надо бы в функцию

2020-11-20 09:48 UTC, RKulagin commented on JavaExtractor/JPredict/src/main/java/JavaExtractor/App.java
> +                executor.execute(new TimeoutCaller(task, s_CommandLineValues.Timeout, task.filename()));
Автор затупил ранее и не вынес эту константу. timeout это время в секундах теперь

2020-11-20 09:49 UTC, RKulagin commented on preprocess.py
> +    if args.net == "code2var":
Тут согласен

2020-11-20 10:02 UTC, RKulagin commented on preprocess.py
> +        word_to_freq.pop("null", 0)
Вроде это старый код, который я не убрал. Сейчас проверю и уберу

2020-11-20 10:41 UTC, RKulagin commented on preprocess.py
> +        word_to_freq.pop("null", 0)
Да, проблема с  null ушла

2020-11-21 12:48 UTC, RKulagin commented on JavaExtractor/JPredict/src/main/java/JavaExtractor/Common/Common.java
> +		if (str1==null){
При повторном ревью рекомендую смотреть всё без последнего коммита, там только изменение стиля java-кода

2020-11-23 09:18 UTC, mocurin requested changes
с process_net все не очень понятно

2020-11-23 09:18 UTC, mocurin commented on preprocess.py
> +        word_to_freq = filter(lambda x: len(x) == 2 and int(x[1]) > int(min_frequency) and "|" not in x[0], word_to_freq)
где-то тут фильтрация многословных имен переменных и происходит, да?
скорее всего дальше будет куча таких правил. Надо бы подумать как эти правил задавать и легко менять (в идеале - передавать через аргументы). Я бы задавал каждое правило через лямбду, наверное
не критично, но задуматься стоит

2020-11-23 09:18 UTC, mocurin commented on preprocess.py
> +    assert len(data_paths) == 3
не-а, не так
```
if len(data_path) != 3:
raise RuntimeError("...")
```

2020-11-23 09:18 UTC, mocurin commented on preprocess.py
> +def process_net(target_histogram_train: str,
histogram - странно. Лучше что-то с vocab

2020-11-23 21:45 UTC, mocurin commented on preprocess.py
> +            lambda line: line.frequency > args.min_occurences,
почти везде к args идет обращение как к глобальной переменной, это не дело.
_default_filters должен получать свой args.min_occurences еще до входа в parse_vocab

2020-11-23 21:46 UTC, mocurin commented on preprocess.py
> +def process_net(target_vocab_train: str,
тут везде используется глобальный args

2020-11-23 21:47 UTC, mocurin commented on preprocess.py
> +                net_type="vec")
давай net_type в какой-нибудь enum превращай

2020-11-24 08:08 UTC, Ruslan-Kulagin approved these changes

2020-11-24 08:12 UTC, mocurin approved these changes

2020-11-24 08:40 UTC, merged