Multi folders preprocessing
bmstu-iu8-g4-2020-project/code2var pull request #25
Opened 2020-11-24 08:50 UTC by RKulagin

During one of the conversations we decided to use new filter for variables (targets). If target can be found in multiple folders, it's quiet common and we can focus on this targets. This approarch helps to filter specific targets and uncommon names.

2020-12-08 19:05 UTC, mocurin requested changes

2020-12-08 19:05 UTC, mocurin commented on preprocess.py
>          pickle.dump(target_freq_train, file)
на будущее надо думать как без пикла обходиться
по понятным причинам не самая безопасная штука

2020-12-08 19:05 UTC, mocurin commented on preprocess.sh
> +## Extract AST path for code2vec
???

2020-12-08 19:05 UTC, mocurin commented on preprocess.sh
> +## Extract AST path for code2vec
лучше удалять, а не комментировать
Все равно все в гите есть

2020-12-10 18:56 UTC, RKulagin commented on code2var.sh
> +mkdir tmp_data_for_code2var/
Да, данная папка служит только для демонстрационной части и удаляется после её конца

2020-12-10 19:06 UTC, RKulagin commented on path_context_reader.py
>          if self.is_train:
Планировал перенести это пониже, почему-то не вставил. Сейчас исправил

2020-12-10 19:16 UTC, RKulagin commented on path_context_reader.py
> +            dataset = dataset.map(lambda x: (((x.path_source_token_indices,
не сообразил как :disappointed:

2020-12-10 19:18 UTC, RKulagin commented on preprocess.py
> -            lambda line: line.frequency > args.min_occurrences,
min_occurrences задаётся для таргетов, оно в другом месте задаётся. Для токенов и путевых хешей - 50, унёс в config

2020-12-11 12:21 UTC, mocurin commented on path_context_reader.py
> +            dataset = dataset.map(lambda x: (((x.path_source_token_indices,
lambda x: (self._generate_input_tensors(x), x.target_string) 
Сори, кажется не совсем понятно объяснил

2020-12-11 12:21 UTC, mocurin commented on JavaExtractor/extract.py
>      outputFileName = TMP_DIR + prefix + dir.split("/")[-1]
как-нибудь через f-строку оформим?

2020-12-11 12:21 UTC, mocurin commented on JavaExtractor/extract.py
> +        with open(prefix + dir + suffix, 'a') as o:
аналогично
не то что бы необходимость, но хорошей практикой считается по максимуму избавляться от str.__add__

2020-12-11 12:21 UTC, mocurin commented on preprocess.py
> +            lambda line: len(line.name) > 2 or line.name in {"i", "j", "k", "e", "s", "o", "db", "fs", "it", "is", "in", "to"},
я так задумался
надеюсь этот сет не создается при каждом заходе в лямбду
надо бы как-то проверить

2020-12-25 15:40 UTC, Ruslan-Kulagin approved these changes

2020-12-25 15:41 UTC, merged